### ISSUE TITLE
How do I confirm that the current content has been serialized

### ISSUE THREAD

**Issue by hoythan** [steelbrain/php-serialize#105]
like PHPSerialize.is_serialized()

**Comment by steelbrain** [comment]
Try deserializing, if it doesn't throw an error, then it's serialized 🤷‍♂️

**Comment by hoythan** [comment]
I can try to solve this problem by submitting a pull request

**Comment by steelbrain** [comment]
A PR would be much appreciated! Thanks!

**Comment by steelbrain** [comment]
Fixed as of #106

Shall be released soon
