### ISSUE TITLE
Open to adding unit tests?

### ISSUE THREAD

**Issue by scalebig** [steelbrain/php-serialize#122]
Thx for the project work! Looking at your source and changelog looks likes you have encountered a number of gotchas. It would be super helpful to capture those test cases. As I start to use this, I will probably add some unit tests in mocha or jest. If there is interest I can submit back as PRs.

**Comment by steelbrain** [comment]
Hi @scalebig 

I would highly appreciate any PRs improving the test situation of the package :)
