### ISSUE TITLE
Wrong serialization of arrays

### ISSUE THREAD

**Issue by kurakin-oleksandr** [steelbrain/php-serialize#128]
Serialization works differently depending on an order of property with array value:
`Serialize.serialize({ test1: '', test2: [ 2 ] })`:
`a:2:{s:5:"test1";s:0:"";s:5:"test2";a:1:{i:0;i:2;}}`

`Serialize.serialize({ test2: [ 2 ], test1: '' })`:
`a:2:{s:5:"test2";a:1:{i:0;i:2;}s:5:"test1";s:0:"";}`

Second case if invalid as `;` is missing between properties

**Comment by steelbrain** [comment]
Was this issue solved? Why was it closed?
