### ISSUE TITLE
Naming Problem on Private or Protected Fields

### ISSUE THREAD

**Issue by tugrul** [steelbrain/php-serialize#132]
```php
class Foo {
    
    private $private;
    protected $protected;
    public $public;
    
}

echo serialize(new Foo());
```

Output:
```
O:3:"Foo":3:{s:12:"Fooprivate";N;s:12:"*protected";N;s:6:"public";N;}
```

Private field is prefixing with `'\u0000Foo\u0000'`

Protected field is prefixing with `'\u0000*\u0000'`

**Comment by jrmyio** [comment]
One problem with this 'fix' is that you cannot serialize to the same string after serialization as the private/protected key meta data is lost.

**Comment by steelbrain** [comment]
@jrmyio Happy to accept some proposals on how to support that. Javascript doesn't have native support for protected or private keys so the solution would have to be custom.

**Comment by jrmyio** [comment]
> The decorators spec (https://github.com/tc39/proposal-decorators) has had breaking changes more times than I have the patience for, I would prefer not to ship production code making use of it unless it becomes stable or we'll have a poor soul complaining in the tracker in a couple years
> 
> Edit: To extend your proposal further, maybe something like this?
> 
> ```
> const serialized = serialize(steel, {
>   'User': {
>      class: User,
>      protected: ['x', 'y'],
>      private: ['z'],
>   },
> });
> ```

I am also a little worried about decorators and them being fully supported by most consumers of this lib.

This proposal by overloading the value where one passes the class is also what I was thinking of.

Another option could be a static property on the Class that holds these private/protected arrays.
