### ISSUE TITLE
TypeError: item.substr is not a function

### ISSUE THREAD

**Issue by lukepolo** [steelbrain/php-serialize#21]
```
// console.log(item)
<Buffer 73 3a 34 30 3a 22 64 32 37 30 64 33 33 36 66 63 38 30 38 31 63 34 38 39 36 36 65 61 62 31 61 65 36 36 62 63 62 30 65 31 35 66 36 30 33 65 22 3b>
```

home/vagrant/Code/LukePOLO/node_modules/php-serialize/lib/index.js:79
  var type = item.substr(0, 1);
                  ^

TypeError: item.substr is not a function
    at unserializeItem (/home/vagrant/Code/LukePOLO/node_modules/php-serialize/lib/index.js:79:19)
    at Object.unserialize (/home/vagrant/Code/LukePOLO/node_modules/php-serialize/lib/index.js:174:10)

**Comment by steelbrain** [comment]
Thanks for the bug report, will investigate soon

**Comment by steelbrain** [comment]
Ah, you are feeding it a buffer instead of a string, you can just do `unserialize(item.toString('utf8'))` instead of `unserialize(item)`

**Comment by lukepolo** [comment]
Gotcha that seemed to fix it, now do i have to setup a class object to allow deserialization of a class?

{ [AssertionError: Class League\OAuth1\Client\Credentials\TemporaryCredentials not found in given scope]

Most of the time  i may not know what class is inside of this data.

**Comment by steelbrain** [comment]
Thanks @lukepolo I've opened #22 for it
