### ISSUE TITLE
Bug when parsing an object

### ISSUE THREAD

**Issue by Da99er** [steelbrain/php-serialize#227]
I have a problem when trying parse:

> a:2:{i:25;i:105;i:31;i:106;}

```js
const Serialize = require('php-serialize');

const str = 'a:2:{i:25;i:105;i:31;i:106;}';

const result = Serialize.unserialize(str);
```

I expect:

> { '25': 105, '31': 106 }

What i have:

> [ <25 empty items>, 105, <5 empty items>, 106 ]

**Comment by steelbrain** [comment]
Will investigate, thank you
