### ISSUE TITLE
support nested serializable Classes + Objects

### ISSUE THREAD

**Issue by cantremember** [steelbrain/php-serialize#5]
add support for nested serializable Classes + Objects

**Comment by steelbrain** [comment]
Sounds fair

**Comment by cantremember** [comment]
oh no, friend -- i've already fixed it

i'm just prepping the PR

**Comment by steelbrain** [comment]
Oh, PRs are nice, Thanks :+1:

**Comment by cantremember** [comment]
yeah.  it's super easy -- it just took me 20x the time to get the toolchain working so that i could write you the necessary specs

**Comment by steelbrain** [comment]
Tip for the future: Just write stuff and let the CI run it. Also `apm` is included with Atom, so if you use Atom, it is used to run specs

**Comment by cantremember** [comment]
yep. plus minimum Harmony compliance in v8

```sh
$ npm run compile

> php-serialize@1.1.0 compile /Users/dfoley/src/github/php-serialize
> ucompiler go

/Users/dfoley/src/github/php-serialize/node_modules/ucompiler/cli/main.js:15
const options = {
^^^^^
SyntaxError: Use of const in strict mode.
```

**Comment by steelbrain** [comment]
Oh yeah, forgot about that, minimum required Node version is 5.0

**Comment by cantremember** [comment]
np.  please see #6 😄

**Comment by cantremember** [comment]
and to be clear ...

## your open source project saved me hours and hours of time

and i really appreciate it
