### ISSUE TITLE
Multi byte Encoding Problem

### ISSUE THREAD

**Issue by breaksyz** [steelbrain/php-serialize#52]
I want to unserialize names with accents but when I got something like that:
`var toUnserialize = 'a:2:{i:0;s:6:"Helló";i:1;s:5:"World";}';`

Throw me an error: SyntaxError

Thanks!

**Comment by steelbrain** [comment]
Thanks for providing a test case, will investigate

**Comment by steelbrain** [comment]
Congratulations on your first issue @breaksyz and thank you for reporting.

Your test case helped me investigate and patch the issue (in #53). I've also made it future-safe so it shouldn't break in any other kind-of multi-byte strings (even 4byte). Thanks again

The fix has been published in version `1.2.5`

**Comment by breaksyz** [comment]
Awesome!!! Thanks!
