### ISSUE TITLE
please add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by cantremember** [steelbrain/php-serialize#6]
please add a CONTRIBUTING.md, calling out
- minimum Node version
- `apm` via Atom.io
- running `npm run lint` from the shell (i ran into issues)
- any special CI setup required (if any)

**Comment by steelbrain** [comment]
Thank you for your request

**Comment by cantremember** [comment]
you're welcome.  when i run `npm run eslint` from the shell (Mac OSX), i get

```sh
$ npm run lint

> php-serialize@1.1.0 lint /Users/dfoley/src/github/php-serialize
> eslint .

/Users/dfoley/src/github/php-serialize/node_modules/eslint/lib/config/config-file.js:361
            throw e;
            ^

Error: /Users/dfoley/src/github/php-serialize/node_modules/eslint-config-airbnb/rules/es6.js:
    Configuration for rule "no-confusing-arrow" is invalid:
    Value "[object Object]" has more items than allowed.

Referenced from: airbnb/base
Referenced from: /Users/dfoley/src/github/php-serialize/.eslintrc.json
    at validateRuleOptions (/Users/dfoley/src/github/php-serialize/node_modules/eslint/lib/config/config-validator.js:111:15)
```

**Comment by steelbrain** [comment]
Would you like to propose any changes to https://github.com/steelbrain/php-serialize/pull/8?

**Comment by cantremember** [comment]
you've added the linting section -- thank you

can you think of any reason why i'd get the above failures when i run `npm run lint` as recommended?

**Comment by cantremember** [comment]
there's not a lot i can say -- it *does* work under CI, so it's unlikely to be a version incompatability issue

**Comment by steelbrain** [comment]
It's a minor eslint issue, nothing to worry about, fixed in https://github.com/steelbrain/php-serialize/pull/9

**Comment by cantremember** [comment]
lemme try that out ...

**Comment by denizdogan** [comment]
Was this change ever merged? I was trying to add support for deserializing private/protected PHP object properties, but can't really figure out how to run the tests at all. Do I really have to install Atom.io to run the spec?

**Comment by steelbrain** [comment]
Hi @denizdogan 

Unfortunately, yes. Tho most of the people I know have it already and for those who don't, they can just open a WIP PR and see the results on CI! :)

**Comment by denizdogan** [comment]
@steelbrain Thanks for your response, and for making this project, it's helped me a lot in my work!

I understand that `apm` may be your personal preference, but would you ever reconsider this?

- I installed Atom and couldn't immediately figure out how to put `apm` on my PATH. It doesn't seem to happen automatically, at least not on macOS.
- Running a test suite like this should not require any CI. I personally often rely on running test suites to immediately see if my code works, and sometimes for lazy debugging using `console.log` and `util.inspect`. I don't want to commit code every time I want to try something out.
- It would be much easier for other developers to participate in a project if they aren't required to install extra software, which may or may not come with unwanted side-effects, outside of the devDependencies. (I noticed ESLint is missing from there as well!)
- As I understand it, the tests use Jasmine, so why do I need `apm`? We already have NPM and Yarn, aren't those good enough?

**Comment by steelbrain** [comment]
Interesting because I'm on macOS myself and getting `apm` in my PATH was pretty straight forward (you have to restart all your terminal tho, for any change related to shell config and not just this one). Furthermore you don't even need APM in your path, once you open it in Atom you just have to do `Window: Run Package Specs` command from the Atom command palette and it'll work fine.

I am open to moving to jasmine vanilla, but I personally cannot do it myself in the near future because of being busy in some other stuff, tho I would love to review a PR doing that! :)
