### ISSUE TITLE
Unserialize returns array when it should return object

### ISSUE THREAD

**Issue by dannyharding10** [steelbrain/php-serialize#64]
The problem seems to be that when the key in an array begins with `0` _immediately followed by a letter_, the array is interpreted as an array instead of an object. This is invalid json, so the data is lost.
Sample code:

    const good1 = `a:1:{s:12:"97YEAY3JO237";s:2:"hi"}`;
	const good2 = `a:1:{s:12:"02YJXTVI6ZOJ";s:2:"hi"}`;
	const good3 = `a:1:{s:12:"X0YJXTVI6ZOJ";s:2:"hi"}`;
	const good4 = `a:1:{s:2:"X0";s:2:"hi"}`;

	const bad1 = `a:1:{s:12:"0XYJXTVI6ZOJ";s:2:"hi"}`;
	const bad2 = `a:1:{s:2:"0x";s:2:"hi"}`;
	const bad3 = `a:1:{s:2:"0N";s:2:"hi"}`;

	const goodResult1 = unserialize(good1);
	const goodResult2 = unserialize(good2);
	const goodResult3 = unserialize(good3);
	const goodResult4 = unserialize(good4);

	const badResult1 = unserialize(bad1);
	const badResult2 = unserialize(bad2);
	const badResult3 = unserialize(bad3);

	console.log('good1', goodResult1);
	console.log('good2', goodResult2);
	console.log('good3', goodResult3);
	console.log('good4', goodResult4);

	console.log('bad1', badResult1);
	console.log('bad2', badResult2);
	console.log('bad3', badResult3);

Logs the following:

    good1 { '97YEAY3JO237': 'hi' }
    good2 { '02YJXTVI6ZOJ': 'hi' }
    good3 { X0YJXTVI6ZOJ: 'hi' }
    good4 { X0: 'hi' }
    bad1 [ '0XYJXTVI6ZOJ': 'hi' ]
    bad2 [ '0x': 'hi' ]
    bad3 [ '0N': 'hi' ]

As you can see, the 3 bad results are wrapped in square brackets `[]` representing a javascript array, instead of curly braces `{}` representing an object.

**Comment by steelbrain** [comment]
Good catch, it's gonna be some time before I can fix it

Would love to review a PR

**Comment by dannyharding10** [comment]
I would be interested in making a PR. Do you have any idea what this would entail or what might be a good starting point?

**Comment by steelbrain** [comment]
I believe [this line](https://github.com/steelbrain/php-serialize/blob/9e3c5136ca0e557f94e459aac3886b8159b15f18/src/index.js#L142) is buggy. 

```js
container = parseInt(key, 10) === 0 ? [] : {}
```
should be replaced with
```js
const parsed = parseInt(key, 10)
container = parsed === 0 && parsed.toString(10) === key ? [] : {}
```
